# Use the official Nginx image as base
FROM nginx:latest

# Copy the index.html file from the host machine into the Nginx server
COPY index.html /usr/share/nginx/html/

# Expose port 80 to the outside world
EXPOSE 80

